### ISSUE TITLE
Disqus support

### ISSUE THREAD

**Issue by alexandre** [wzpan/hexo-theme-freemind#19]
What do you think? is possible?

[ ]'s

**Comment by acgtyrant** [comment]
How to deploy disqus? I do not found any relative setting in `_config.yml`, only `duoshuo_shortname`. Thank you!

**Comment by acgtyrant** [comment]
Just add `disqus_shortname` in `_config.yml` which is in Hexo directory, not theme directory.

**Comment by wzpan** [comment]
Yes. It should be placed at your **root** _config.yml .
