### ISSUE TITLE
要创建页面还可以使用一下方法

### ISSUE THREAD

**Issue by gaotongfei** [wzpan/hexo-theme-freemind#24]
见segmentfault上的一个答案：http://segmentfault.com/q/1010000000618915/a-1020000000752865
这种方法可以支持markdown
就是原答案里的
```
About: /about
```
改成
```
  - title: About
    url: about
    intro: "About me."
    icon: "fa fa-user"
```
就好。
建议加到README.md中去 : )

**Comment by wzpan** [comment]
Great! But only about page can be created in that way.
