### ISSUE TITLE
更新hexo3.0后, 侧边栏中tag和categories 问题.

### ISSUE THREAD

**Issue by bearxuqian** [wzpan/hexo-theme-freemind#26]
更新hexo和freemind主题后, hexo g命令生成的
public\categories\\******\index.html
public\tags\******\index.html 
全都一样.
右侧的标签和分类点击后都是同一页面,

**Comment by wzpan** [comment]
嗯，这个问题在我这里也重现了。Hexo 3.0的改动太大，升级时出现了这方面的遗漏。已修复。
