### ISSUE TITLE
请问怎么设置多级categories

### ISSUE THREAD

**Issue by zhu8655** [wzpan/hexo-theme-freemind#31]
如题，请问大神有什么解决方法吗？
一般情况下都是：
* categorie_1
* categorie_2
* categorie_3

如何设置成这样：
* categorie_1
 * categorie_1_1
 * categorie_1_2
* categorie_2
 * categorie_2_1
* categorie_3

另外，感谢您提供这么好的一个 Hexo 主题。

**Comment by wzpan** [comment]
freemind并不支持多级categories，因为我没有这个需求。除非你可以给我一个足够有说服力的原因，以及多级分类下我的Archives和Categories两个板块该怎么展示。;-p

**Comment by zhu8655** [comment]
感谢您回复 :-)
之所以想有一个多级categories，主要是为了更好地分类知识点。
本来是想使用您的wixo作为主题的（不知道它能不能支持多级categories），但感觉有点单一，毕竟我的blog除了知识的整理外，还有一些类似游记的文章。
不过说实话，没有多级categories我觉得也没多大关系，只是想做的更好才来问您这个问题的。
祝您的主题越来越好 ;-)
