### ISSUE TITLE
请问那个sidenote/mnote是怎么实现的啊？

### ISSUE THREAD

**Issue by zhu8655** [wzpan/hexo-theme-freemind#32]
抱歉又来打扰您了 ^_^
不知道到底是哪个名字，就两个都打了。
似乎您编写的 tag-plugins 并没有这个东东，但您的blog里还是有的。
蒟蒻就求教啦～

**Comment by wzpan** [comment]
这个是额外写的插件，由于不能在其他基于 twitter-bootstrap 的主题中通用，而且滥用的话可能导致样式错乱。所以没有收录在 hexo-tag-bootstrap 中。

**Comment by zhu8655** [comment]
请问 *其他基于 twitter-bootstrap 的主题* 包括`freemind`吗？
如果不是，请问能提供源码吗？
如果是的话那就close吧

**Comment by zhu8655** [comment]
好吧。。我已切实体会到格式错乱的意思了。。
插件的确不能乱加。。
