### ISSUE TITLE
搜索功能bug

### ISSUE THREAD

**Issue by whzecomjm** [wzpan/hexo-theme-freemind#33]
搜索确认以后只会显示 site:example.com 搜索的关键词并没有显示，也没有按关键词排序。

**Comment by whzecomjm** [comment]
顺便可以增加一个 swiftype 的站内搜索。

**Comment by wzpan** [comment]
> 搜索确认以后只会显示 site:example.com 搜索的关键词并没有显示，也没有按关键词排序。

应该是GFW的问题，在我这边搜索是正常的。

不过，我的确该考虑换一个搜索引擎了。实际上我最近在和朋友一起实现一个本地搜索引擎，无需第三方服务支持。在完善开源之前，先换成 SwiftType 吧。

**Comment by whzecomjm** [comment]
不可能啊 我现在不在国内...

btw,支持本地搜索引擎！

**Comment by wzpan** [comment]
已更换为 SwiftType 搜索引擎。

**Comment by whzecomjm** [comment]
谢谢！不过我也自己更换好了。;)

**Comment by wzpan** [comment]
@whzecomjm 试试最新的主题的本地搜索功能吧。;-D

**Comment by whzecomjm** [comment]
好的！
