### ISSUE TITLE
haskell代码块显示不正常

### ISSUE THREAD

**Issue by Logistic1994** [wzpan/hexo-theme-freemind#35]
``` haskell
data Shape = Circle Float | Rectangle Float Float deriving (Show)
```
显示会变成这样
![20151025162040](https://cloud.githubusercontent.com/assets/8079507/10714659/113fbca2-7b34-11e5-8347-1a14a7ba3eb8.png)
而换用其他主题后一切正常。

**Comment by wzpan** [comment]
Sorry 啊，我刚刚才留意到这个 issue 。

看了一下生成的 html 代码，`(show)` 这一部分会使用 container 样式类来修饰：

![image](https://cloud.githubusercontent.com/assets/1631405/10937164/110326fc-832c-11e5-9678-7b4def7c2760.png)

而这个名字又和 bootstrap 默认的 container 样式名冲突，后者是站点外边框的样式名。这就导致代码矿中的 container 样式显示出问题。

如果修改这个类名为其他名字，比如 `hscontainer` ，那么代码块就可以正常显示。

在 highlight.js 的 issue 板块，已经有人提过这个问题。见 https://github.com/isagalaev/highlight.js/pull/266 里 treep 的评论。

因此，如果希望在 Freemind 等基于 Bootstrap 的主题里使用 Highlight.js 实现对 Haskell 的语法高亮，需要设置一下 Highlight.js 修改 container 样式的名字。一种修改方法就是将 node_modules/hexo/node_modules/hexo-util/node_modules/highlight.js/lib/languages/haskell.js 里的所有 className 为 `container` 的样式改名为 `hscontainer` 。

**Comment by wzpan** [comment]
问题应该已经解决。先关闭了。如有问题请重新开启。
