### ISSUE TITLE
为什么我下载了主题后启用后，顶栏的categories和tags处于没有任何索引的状态？

### ISSUE THREAD

**Issue by hxhb** [wzpan/hexo-theme-freemind#36]
首页能正常索引到了之前写的文章，但是分类和标签里面没有任何内容，之前使用的Next主题....
写法为这样：
title: STL概述
date: 2015-08-18 14:26:38
categories: 编程笔记
tags: C++

**Comment by wzpan** [comment]
你创建了分类和标签的页面没？

**Comment by hxhb** [comment]
目录结构是这样的：
\source\CNAME
\source\favicon.ico
\source\about\index.md
\source\categories\index.md
\source\tags\index.md
\source\_posts\.....
----------------------------------------
categories\index.md中是这样写的：
title: 分类
date: 2015-08-18 09:30:56
type: "categories"
comments: false
---
tags\index.md中是这样写的：
title: tags
date: 2015-08-17 22:16:13
type: "tags"
comments: false
---
archives和about都能正常显示的啊....

**Comment by hxhb** [comment]
好吧，知道为啥了，我以为markdown也能解析呢。

**Comment by wzpan** [comment]
问题既然解决，那我就关了本issue。
