### ISSUE TITLE
新手求助--多颜色代码块

### ISSUE THREAD

**Issue by yangdm0209** [wzpan/hexo-theme-freemind#37]
看您的网页中代码块颜色比较丰富，为什么使用了您的主题，我的代码块只是简单的一种配色呢？新手，求助

**Comment by wzpan** [comment]
你的代码需要添加语言前缀才会有高亮。见我的示例文章的源码：https://raw.githubusercontent.com/wzpan/hexo-theme-freemind/source/_posts/code-highlight.md

**Comment by yangdm0209** [comment]
谢谢，长知识了~~
