### ISSUE TITLE
How to added achieve widget with count info?

### ISSUE THREAD

**Issue by beyondai** [wzpan/hexo-theme-freemind#38]
like the following：

January 2016 (10)
December 2015 (22)
November 2015 (31)
October 2015 (7)

**Comment by wzpan** [comment]
You will need to define a variable for counting at [archive.js](https://github.com/wzpan/hexo-theme-freemind/blob/master/layout/_partial/archive.ejs).

**Comment by wzpan** [comment]
I have already given a doable method. Close this issue.
