### ISSUE TITLE
内置的搜索栏输入关键字无反应

### ISSUE THREAD

**Issue by PytLab** [wzpan/hexo-theme-freemind#39]
我在稍微修改过主题的样式以后偶然发现在搜索栏中输入关键字后不显示搜索结果的div了，请问这类问题大概是在哪里修复?

**Comment by wzpan** [comment]
有很多种可能会导致这个问题。是不是把搜索结果的div的名字（local-search-result）改了？

**Comment by wzpan** [comment]
我发现你的站点并没有 [search.xml](http://ipytlab.com/search.xml) 。试试手动 hexo generate 一下，确保你的目录下有这个文件。

**Comment by PytLab** [comment]
我没有修改过sidebar相关的东西，不过我没见到过search.xml这个文件，我不是很了解，请问这个文件是自动生成的还是在网站source里面的？

**Comment by PytLab** [comment]
应该不是我修改样式的原因，我把版本回退到初始版本还是无法搜索，感觉是你说的那个问题，可我不清楚具体该怎么做了T_T

**Comment by wzpan** [comment]
详见这篇文章：http://hahack.com/codes/local-search-engine-for-hexo/

**Comment by PytLab** [comment]
非常感谢，问题解决了，感谢分享 ^_^
