### ISSUE TITLE
怎么改变整体背景色呢？

### ISSUE THREAD

**Issue by drduan** [wzpan/hexo-theme-freemind#40]

**Comment by wzpan** [comment]
Bootstrap 的好处是有很多第三方的主题插件。你可以很轻松的更换为其他的主题色。例如 [Bootswatch](http://bootswatch.com/)

**Comment by drduan** [comment]
是需要把  css里边的文件换一下 就行么？？

**Comment by wzpan** [comment]
是的。我下个版本整合多个Bootswatch吧。

**Comment by drduan** [comment]
是需要把  css里边的文件换一下 就行么？？或者可以通过改bootstrap.min.css文件

**Comment by drduan** [comment]
是需要把  css里边的文件换一下 就行么？？或者可以通过改bootstrap.min.css文件

**Comment by wzpan** [comment]
还是等我更新主题吧。要改动的地方挺多，单独替换css是可以实现的，只是一些地方显得不协调。

**Comment by drduan** [comment]
行 等着哦

**Comment by wzpan** [comment]
已完成。更新主题后可以轻松切换各种颜色主题。详见 [Color Themes](http://wzpan.github.io/hexo-theme-freemind/2016/01/30/color-themes/) 和主页Readme。
