### ISSUE TITLE
颜色主题问题反馈

### ISSUE THREAD

**Issue by chineselzh** [wzpan/hexo-theme-freemind#42]
作者您好！首先感谢带来如此美丽漂亮大方帅气强大完善的hexo主题！
 在使用颜色主题时，当使用`darkly`时，我的markdown文章中有些`带格式的引用部分`无法看到，必须要选择之后才能看到，请问这个怎么修改才行？谢谢！
测试了一下使用大部分暗色或非白色的颜色主题都是如此。
具体效果请看：[关于作者页面](http://www.jianjiao8.xyz/about/)及[这篇文章标题下面那一行](http://www.jianjiao8.xyz/2015/10/04/best-soft/)下面的那一行

刚试了一下QQ浏览器android版查看没问题，但三星手机浏览器也有问题。。。
请大神尽快修复，谢谢！

另外怎么将我的网站加入到freemind的[Examples](https://github.com/wzpan/hexo-theme-freemind/wiki/Examples)页面呢？再次感谢 ！

**Comment by wzpan** [comment]
已修复，谢谢反馈。

> 另外怎么将我的网站加入到freemind的Examples页面呢？再次感谢 ！

直接 [编辑该页面](https://github.com/wzpan/hexo-theme-freemind/wiki/Examples/_edit) 即可。

**Comment by chineselzh** [comment]
@wzpan  非常感谢！wzpan万岁！

**Comment by chineselzh** [comment]
@wzpan 我升级最新版本还是不行呢？大神请看一下呢？谢谢！

**Comment by wzpan** [comment]
不好意思，改了 dev 的分支，忘记合并一处改动到 master 分支了。请再更新下主题试试。

**Comment by chineselzh** [comment]
@wzpan 测试已经OK了，非常感谢大神！
