### ISSUE TITLE
no pagination about tag page

### ISSUE THREAD

**Issue by mYmNeo** [wzpan/hexo-theme-freemind#46]
When we have many articles(>`per_page`) with same tag,
For examples:
**xxx.com/tags/abc**
There is no pagination on the page, the page only show the first `per_page` articles. 
but hexo actually generate all the pages, and we can only access those pages with typing url(**xxx.com/tags/abc/page/2**) in browser.
The only way to show all articles is to disable pagination in `_config.yml`.
Is there anyway to make a pagination on those page like the main page does?
Thank you for any help you can provide!!!

**Comment by wzpan** [comment]
Hello @mYmNeo ,

The tag page is designed to have only one listing page, without paginations. 

Can you provide an example page that has this issue?

**Comment by mYmNeo** [comment]
https://github.com/mYmNeo/mymneo.github.io/tree/pagination/tags/algorithm, here is my blog which is generated by `hexo deploy -g` with pagination and parameter `per_page: 5`, you can see that there is a subdirectory called `page` but its `index.html` has no button or navigation pointed to any of them, so the only way user want to see next page or prev page is to type URL in browser.

**Comment by wzpan** [comment]
The pagination for tags/categories page has been added. Please update the theme and see whether it works.

I don't quite like what it looks for now, especially when I give a little value like 5 to `per_page`.  But Hexo doesn't allow me to control how many items to display at tags/categories page. I'm afraid that it's the only scenario I can do for you.

**Comment by mYmNeo** [comment]
I have applied the new commit, it works but needs to be modified a little
```
		<!-- pagination for tag-->
		<% if (page.tag) { %> # only tag page use pagination, or archive page has a lot of same page index
		<div>
  		<center>
		<%- partial('index_pagination') %>
  		</center>
		</div>
		<% } %>
```
Thanks a lot at last. 👍

**Comment by wzpan** [comment]
Updated. Closed this issue.
