### ISSUE TITLE
请问如何修改图片大小

### ISSUE THREAD

**Issue by disburden** [wzpan/hexo-theme-freemind#47]
我对网页制作一窍不通,我现在想把文章中通过feature指定的图片,在首页table中显示的大小改小一些,感觉现在的图片显示的太大了一点,请问要在哪里修改?非常感谢!

顺便问一下,Link部份的icon能不能直接设置为一个url链接的图片?

**Comment by wzpan** [comment]
> 在首页table中显示的大小改小一些

首页的 feature 图使用的是 bootstrap 的 [thumbnail](https://github.com/wzpan/hexo-theme-freemind/blob/dev/source/css/themes/bootstrap/thumbnails.less) 样式。这个样式是自适应的，并没有高度和大小的限定。我比较建议的是你自行缩小图像，用小一点的图也有助于提升首页的加载速度。

> Link部份的icon能不能直接设置为一个url链接的图片?

暂时不支持。默认都是用的 [Font Awesome](http://fontawesome.io/) 的图标。如果有需要，你可以自行添加自定义图片。比如参考这份教程：http://www.cnblogs.com/czcz1024/p/3544387.html

**Comment by disburden** [comment]
知道了,谢谢
