### ISSUE TITLE
Categories BUG

### ISSUE THREAD

**Issue by Armixy** [wzpan/hexo-theme-freemind#48]
刚才发现一个比较严重的BUG，之前PR过一个能够处理多个类别的Categories.ejs，但是在获取site.categories的时候，如果多篇文章都有一个二级类别，会重复获取，求解决

**Comment by wzpan** [comment]
Freemind 并不支持多级 categories 。

**Comment by mhkz** [comment]
您好，我想请问一下，我想给这个主题加个wiki，应该如何实现呢

**Comment by Armixy** [comment]
作者实现的比较好，我自己就只是在hexo blog里再init了一个blog，然后设置成wiki，把输出重定向到统一的public source

**Comment by wzpan** [comment]
清理 `wontfix` 标签。
