### ISSUE TITLE
能否实现【置顶】功能？

### ISSUE THREAD

**Issue by chineselzh** [wzpan/hexo-theme-freemind#49]
非常感谢大大带来的如此漂亮实用的主题！感谢！
这里提一个建议：能否实现`置顶`的功能？我的意思是不用修改时间而实现这个功能，谢谢！

**Comment by wzpan** [comment]
可以考虑支持

**Comment by chineselzh** [comment]
@wzpan 如果能实现就太好了，感谢！

**Comment by wzpan** [comment]
@chineselzh 已实现置顶功能，在需要置顶的文章的 front-matter 里添加 `top: true` 即可。

* 一个例子：<https://raw.githubusercontent.com/wzpan/hexo-theme-freemind/source/_posts/lorem-ipsum.md>
* 效果见 [demo首页](http://wzpan.github.io/hexo-theme-freemind/)

**Comment by chineselzh** [comment]
@wzpan 大神啊！这么快就搞定了，真是太好了，感谢感谢！呵呵。。。

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： hexojs/hexo-generator-index#51
