### ISSUE TITLE
评论字体颜色的问题

### ISSUE THREAD

**Issue by chineselzh** [wzpan/hexo-theme-freemind#50]
您好，我又来反馈问题来了，呵呵。。。
使用freemind主题的时候，如果有评论的话，字体看起来很费劲。。。
`评论`是：
duoshuo_shortname
`主题配置`是：
theme: darkly
inverse: true

**选中后才能看得清楚。。。，如图**

![333](https://cloud.githubusercontent.com/assets/11897604/16511422/8a5bd5b8-3f82-11e6-80fa-1ff99895ac57.png)

**Comment by wzpan** [comment]
问题已修复。所有深色主题统一使用白色字体。

**Comment by chineselzh** [comment]
@wzpan 我使用git pull也成功了，但评论字体和置顶功能怎么都没有作用呢？请查看 ，谢谢！

**Comment by wzpan** [comment]
@chineselzh sorry 只提到了 dev 分支，忘了合并到 master 分支，现在更新下试试吧。

**Comment by wzpan** [comment]
刚刚又补提了一次，补上了 i38n 的设置。可以再更新下。现在在 master 分支预览，效果正常。

**Comment by chineselzh** [comment]
@wzpan  大神太勤快了，感谢！晚上回家试下。。。

**Comment by chineselzh** [comment]
@wzpan 已经OK了，感谢大神！呵呵。。。
