### ISSUE TITLE
Showing Spanish

### ISSUE THREAD

**Issue by NoahDragon** [wzpan/hexo-theme-freemind#51]
![image](https://cloud.githubusercontent.com/assets/5704064/17577915/2326a9b0-5f51-11e6-885d-632fd0de3937.png)

I already set the language to en in the root config, did I miss some place to set up the language?

**Comment by wzpan** [comment]
Hello @NoahDragon ,

Currently Freemind only offers [4 kinds of Languages](https://github.com/wzpan/hexo-theme-freemind/tree/master/languages).

Since I'm not farmiliar with Spanish, could you please create one and send me a pull request?

**Comment by NoahDragon** [comment]
@wzpan Sorry, my question is not clear. 
On the pic, the button "Leia Mais" supposes to show "Read More", but I don't know why it is showing the Spanish. Seems like it using the pt-BR.yml. In my _config.yml, I explicitly set the language to en, this problem causes the problem. I will remove it and try it again.

**Comment by wzpan** [comment]
I see, you can also set it to `default` explicitly.
