### ISSUE TITLE
关于mnote插件

### ISSUE THREAD

**Issue by bingofan** [wzpan/hexo-theme-freemind#52]
求分享mnote插件呀~~~~~
查看了文章http://hahack.com/codes/from-ruhoh-to-hexo/#stq=&stp=0
发现这个mnote相当不错呀,可以一直用不了,能把插件再分享一下吗~多谢~~~~

**Comment by wzpan** [comment]
mnote容易和右侧的目录冲突，所以并不打算提供给Freemind，以防滥用影响Freemind的效果。

**Comment by wzpan** [comment]
清理 `wontfix` 标签。
