### ISSUE TITLE
head.ejs中也加载了一遍analytics.ejs

### ISSUE THREAD

**Issue by masikkk** [wzpan/hexo-theme-freemind#53]
head.ejs中也加载了一遍analytics.ejs，导致添加CNZZ的“站长统计 | 今日IP[12] | 今日PV[40] | 昨日IP[49] | 昨日PV[121] | 当前在线[1]”代码时，显示到了左上角导航栏下。感觉在footer.ejs中加载analytics.ejs就可以了吧。

**Comment by wzpan** [comment]
Freemind只在header里加了analytics的代码，并未在footer中加。

**Comment by masikkk** [comment]
好的，不好意思，用的free2mind主题，您的原版没问题。
