### ISSUE TITLE
Source code for wiki?

### ISSUE THREAD

**Issue by AnacondaPython** [wzpan/hexo-theme-freemind#57]
Are you making the source code for your hahack's wiki page open to the public? 

also subscribe page too

thanks

**Comment by wzpan** [comment]
The wiki theme is published as another theme [hexo-theme-wixo](https://github.com/wzpan/hexo-theme-wixo). 

The reason that I don't plan to open source the whole theme of my blog is that it's complicated than what a theme should be. I prefer to keep my themes more simple and easy to hack, such as writing your subscribe page.
