### ISSUE TITLE
博客具体分类页面只能显示5篇文章

### ISSUE THREAD

**Issue by tommyjiang** [wzpan/hexo-theme-freemind#59]
示例页面如下：

http://tommyjiang.github.io/categories/%E6%8A%80%E6%9C%AF/

该分类目前有6篇文章，但只能显示最近的5篇。

完整的分类页面没有问题：

http://tommyjiang.github.io/categories/

**Comment by wzpan** [comment]
已修复，出现这个原因是文章数量超出了根目录 config.yml 里的 pagination 的最大数量，被 hexo 拆成了多页。而我的列表模式是不会提供 paginiation 的。所以我改成了类似首页那样的条目模式，提供 pagination ，这样当超出数量时可以点击下面的分页器跳到下一页。

**Comment by tommyjiang** [comment]
感谢！
