### ISSUE TITLE
代码高亮设置

### ISSUE THREAD

**Issue by buweilv** [wzpan/hexo-theme-freemind#60]
请问代码高亮如何设置，生成的页面完全没有代码高亮。

**Comment by wzpan** [comment]
代码段和正文之间是否有用空行隔开？

**Comment by buweilv** [comment]
不好意思，我是按照之前的markdown输入代码的风格写blog，即缩进一个tab。看了你的markdown的写法，按照你的写法以```开始和结尾的方法就可以正常显示了。另外问之前我搜了下Issue，发现你在#37中给的链接是不能直接跳转看markdown的。

**Comment by wzpan** [comment]
以前可以的，Github后面对链接做了调整，所以那个链接已死。
