### ISSUE TITLE
段内换行不支持

### ISSUE THREAD

**Issue by buweilv** [wzpan/hexo-theme-freemind#61]
你好，markdown支持段内强制换行，显示出来的仍然是一行，如果要换行可以先按入两个以上的空格然后回车。但是写blog的时候如果强制换行，确实就换行了。所以必须要写满一行让其自动换行才能保证是完整的一段，如果不能强制换行对于大屏幕来说简直痛苦呀。

**Comment by buweilv** [comment]
通过修改hexo的markdown渲染引擎为hexo-render-markdown-it即可，然后修改hexo的_config.yml即可，参考[hexo-render-markdown-it配置](https://github.com/celsomiranda/hexo-renderer-markdown-it/wiki/Advanced-Configuration)即可。

**Comment by wzpan** [comment]
问题和主题无关。
