### ISSUE TITLE
How to configure more scratch_name in _config.yml?

### ISSUE THREAD

**Issue by 3y2y** [wzpan/hexo-theme-freemind#62]
I tried some ways to configure more than one scratch_name in _config.yml but failed.
Do you know how to configure more than one scratch_name (notebook) in _config.yml?
Thank you!

e.g., scratch_name: scratch1 scratch2 ......

**Comment by wolfcon** [comment]
How did you do that?

**Comment by wzpan** [comment]
hexo-theme-wixo user?

**Comment by wolfcon** [comment]
Already solved.
