### ISSUE TITLE
“阅读更多”的样式text-pull:right在chrome中查看“Unknown property name”

### ISSUE THREAD

**Issue by chenbuer** [wzpan/hexo-theme-freemind#63]
样式定义在文件style.css中，我改成text-align:right也不生效。
请帮忙看一下。

另外，hexo推荐中文为zh-Hans，但是freemind的配置文件写的是zh-CN.yml。这样主配置文件中就需要写成zh-CN才能生效

**Comment by wzpan** [comment]
1. 这其实是一个已经过时的属性，如果把 more 按钮放在右侧，由于我加入了 feature 图像的特性，如果有些文章有 feature 图有些没有，那么按钮的位置就会有变动，影响体验。所以我已经删了这个样式，建议保持在左侧。如果你希望保留在右侧，可以写成：

``` css
.page .more {
  float: right !important;
}
```

2. zh-CN 是沿用了 landscape 的 [语言定义](https://github.com/hexojs/hexo-theme-landscape/tree/master/languages) 。从区分简繁体的角度来说，用 zh-Hans 应该更合适一些，不过我最初也是为了保留 landscape 的习惯。

**Comment by chenbuer** [comment]
是的，改成float: right !important;好使，感谢
