### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null in search.js

### ISSUE THREAD

**Issue by fangying** [wzpan/hexo-theme-freemind#65]
Hi wzpan, I got the following error when Chrome webbrowser was used the view the pages with the latest freemind theme.
```
Uncaught TypeError: Cannot read property 'addEventListener' of null
    at Object.success (search.js:39)
    at fire (jquery-2.0.3.min.js:25)
    at Object.fireWith [as resolveWith] (jquery-2.0.3.min.js:25)
    at done (jquery-2.0.3.min.js:25)
    at XMLHttpRequest.<anonymous> (jquery-2.0.3.min.js:25)
```
However firefox looks fine. Below is my env info:
```
hexo: 3.2.2
hexo-cli: 1.0.2
os: Linux 4.2.0-27-generic linux x64
http_parser: 2.7.0
node: 6.9.5
v8: 5.1.281.89
uv: 1.9.1
zlib: 1.2.8
ares: 1.10.1-DEV
icu: 57.1
modules: 48
openssl: 1.0.2k
```
The feature image also looks strange some way. Can you give me some insight about this ?

![hexo](https://cloud.githubusercontent.com/assets/5813287/23653946/6c6a2b62-0369-11e7-8fa0-b315de9cf997.png)

**Comment by wzpan** [comment]
Have you installed hexo-generator-search?

**Comment by wzpan** [comment]
For a long time without responds, I will close this issue. If you still have problem, you can reopen it.
