### ISSUE TITLE
请教如何使用标签插件

### ISSUE THREAD

**Issue by ShallWe2000** [wzpan/hexo-theme-freemind#70]
请问作者如何使用标签插件， 比如主题说明文件中的warning。

**Comment by wzpan** [comment]
1. 装 hexo-tag-bootstrap

```
npm install --save hexo-tag-bootstrap
```

2. 参考 [Tag Plugins](http://wzpan.github.io/hexo-theme-freemind/2014/03/16/tag-plugins-cn/) 使用。

这些在主题的 Readme 里头都已经写了的，请认真阅读。
