### ISSUE TITLE
How can I show the description of article on the front page？

### ISSUE THREAD

**Issue by zaneven** [wzpan/hexo-theme-freemind#72]
I found the article on the front page is full text. 

 [the example](http://zane.gocery.me)

but I just want to show the description of it. what should I do?

**Comment by wzpan** [comment]
As you can see from the source code of a post at the demo site(
https://raw.githubusercontent.com/wzpan/hexo-theme-freemind/source/_posts/tag-plugins-cn.md), I put `<!-- more -->` at the place I want to trim.

**Comment by zaneven** [comment]
@wzpan Sorry for my expression.

![qq20170507-114901](https://cloud.githubusercontent.com/assets/19469818/25777793/68610e28-331b-11e7-83d4-7ec6f87818ae.png)

> this is the example of your demo site

![qq20170507-115026](https://cloud.githubusercontent.com/assets/19469818/25777794/686215a2-331b-11e7-8848-9c342209d6e1.png)
> this is my site

What I want to add is the “Read More” . I don't want to see the whole post at the main page,just want to show the first paragraph or the description of the post.
 I read the link you gave to me, but don't know how to use it to do what I mentioned above.

Thank you for your help!

**Comment by wzpan** [comment]
As I said, put `<!-- more -->` at the place you want to cut.

**Comment by zaneven** [comment]
Thank you so much. I use Bootstrap tag plugins to do like this：

```
{% alert info %}
some descriptions
{% endalert %}
<!-- more -->
```

It looks simple
![](http://omdpnsgk3.bkt.clouddn.com/QQ20170507-124335.png)
