### ISSUE TITLE
Freemind theme at Jekyll

### ISSUE THREAD

**Issue by KarelWintersky** [wzpan/hexo-theme-freemind#73]
How I can convert Freemind theme for Jekyll?

**Comment by wzpan** [comment]
I don't use Jekyll at all. But I'm afraid that there is no any easy way to do so. You have to rewrite it.

**Comment by KarelWintersky** [comment]
Second question:

![](https://habrastorage.org/web/85b/b13/c66/85bb13c664ae4c6abbf365eecf99ab62.jpg)

Problem with space between russial letters. 
original styles

**Comment by wzpan** [comment]
Font issue. You can add a russial letter font at the beginning of [this line](https://github.com/wzpan/hexo-theme-freemind/blob/master/source/css/style.css#L405).
