### ISSUE TITLE
请问，markdown的主题可以更换吗？

### ISSUE THREAD

**Issue by zaneven** [wzpan/hexo-theme-freemind#74]
markdown的主题可以更换吗？

**Comment by wzpan** [comment]
markdown 有什么主题？

**Comment by zaneven** [comment]
比如以下这些风格各异的markdown的效果，我用的编辑器里提供了多种的预览样式，就想到这个hexo主题是不是也能有这样的效果





赵子文
zaneven@foxmail.com

**Comment by wzpan** [comment]
是不是插图了？没看到图

**Comment by zaneven** [comment]
发您邮箱了，请查收


赵子文
zaneven@foxmail.com

**Comment by wzpan** [comment]
你说的这些是Hexo主题该做的事情，而不是markdown本身所支持的。更换不同的color theme能够使得样式有所区别，或者换其他Hexo主题。

**Comment by zaneven** [comment]
好的，谢谢


赵子文
zaneven@foxmail.com
