### ISSUE TITLE
How to get rid of heart icon in slogan line?

### ISSUE THREAD

**Issue by gotoco** [wzpan/hexo-theme-freemind#80]
Is it possible to get rid of heart icon in slogan line?

**Comment by wzpan** [comment]
For now it's not a configurable option. 

But if you want to remove it, you can directly delete [line 2 of slogan.ejs](https://github.com/wzpan/hexo-theme-freemind/blob/master/layout/_partial/post/slogan.ejs#L2).

**Comment by gotoco** [comment]
Thanks for the response, I probably will hack slogan.ejs to get rid of it, but will be nice to make it configurable in the future.
