### ISSUE TITLE
分享到微信朋友圈功能无法生成二维码

### ISSUE THREAD

**Issue by sd44** [wzpan/hexo-theme-freemind#81]
原来还是可以的，最近一个多月出现问题。

一直是“正在加载”状态。

**Comment by wzpan** [comment]
这个并非hexo-theme-freemind本身的问题，而是分享的问题。是用的百度分享？

**Comment by sd44** [comment]
嗯，用的freemind默认的bdshare百度分享，有什么解决办法吗？其他分享都正常……

**Comment by wzpan** [comment]
从我的demo站点来看依然是可用的。http://www.hahack.com/hexo-theme-freemind-blog/2014/03/15/lorem-ipsum/
我建议你看下页面源码做下比对。

**Comment by sd44** [comment]
> 从我的demo站点来看依然是可用的。http://www.hahack.com/hexo-theme-freemind-blog/2014/03/15/lorem-ipsum/
> 我建议你看下页面源码做下比对。

谢谢，问题应该找到了。
我不会网页分析，只通过简单试验和操作猜想问题原因如下，可能有误。

问题不在freemind，也不在hexo，而是百度分享对于UTF-8中文过长网址无法转换成正确的二维码，会一直提示 正在加载。（我是在Linux下用 hexo n "我是一长串中文题目"来新建的网页）

个别短中文网址和ASCII网址不会出现这个问题。
