### ISSUE TITLE
Word wrapping does not work with long URL

### ISSUE THREAD

**Issue by simpsonys** [wzpan/hexo-theme-freemind#82]
Hello Thanks for providing good theme of Hexo. I have a question.

When I make post with Long URL , the word wrapping does not work correctly, If I access with Mobile phone browser, because of Long URL, the top right menu icon does not display on the screen , I have to scroll to end of page right to check menu.

Could you give me advice to solve this issue ?

Thanks in advance.

**Comment by wzpan** [comment]
Can you provide a page with such problem?

**Comment by simpsonys** [comment]
@wzpan following is URL
https://simpsonys.gitlab.io/

**Comment by wzpan** [comment]
@simpsonys fixed. Please update hexo-theme-freemind via `git pull` and try again.

**Comment by simpsonys** [comment]
@wzpan  Thanks, fixed
